### ISSUE TITLE
[Question]: homebridge support

### ISSUE THREAD

**Issue by Jayp007** [mochipon/pysesameos2#18]
### Describe the question you have - 質問の内容

Hi! Sorry to bother you.
It is possible to make it work with homebridge besides homeassistant? Thanks in advance! 

### Pysesameos2 version (`pip show pysesameos2`)

0.0.2

### Python version (`python --version`)

Python 2.7.16

### OS

Raspberry  pi OS

### BlueZ version (`bluetoothctl -v`) in case of Linux

Bluetoothctl 5.50

**Comment by mochipon** [comment]
Thank you for the question! I am very glad to see that there are other people interested in this library besides me 🤣

Unfortunately, I do not use Homebridge and do not plan to implement it. As you may know, there is a great project, [`homebridge-open-sesame`](https://github.com/yasuoza/homebridge-open-sesame), based on the implementation of `pysesame3`. I know it is a bit irresponsible, but I am hopeful that someone will create another project like that, based on the implementation of `pysesameos2`.

**Comment by Jayp007** [comment]
Hi, this is a really great project! Thank you for take your time to answer me.🙌
