### ISSUE TITLE
[Question]: Cannot discover SESAME4 with discover.py

### ISSUE THREAD

**Issue by allfreelimeshot** [mochipon/pysesameos2#25]
### Describe the question you have - 質問の内容

When I run `discover.py`, I can't discover SESAME4.

```
$ python discover.py
DEBUG:asyncio:Using selector: EpollSelector
INFO:pysesameos2.ble:Starting scan for SESAME devices...
WARNING:pysesameos2.ble:Unsupported SESAME device is found, skip.
WARNING:pysesameos2.ble:Not a SESAME device, skip.
WARNING:pysesameos2.ble:Not a SESAME device, skip.
WARNING:pysesameos2.ble:Not a SESAME device, skip.
WARNING:pysesameos2.ble:Not a SESAME device, skip.
WARNING:pysesameos2.ble:Not a SESAME device, skip.
WARNING:pysesameos2.ble:Not a SESAME device, skip.
WARNING:pysesameos2.ble:Not a SESAME device, skip.
WARNING:pysesameos2.ble:Not a SESAME device, skip.
WARNING:pysesameos2.ble:Not a SESAME device, skip.
WARNING:pysesameos2.ble:Not a SESAME device, skip.
WARNING:pysesameos2.ble:Not a SESAME device, skip.
WARNING:pysesameos2.ble:Unsupported SESAME device is found, skip.
WARNING:pysesameos2.ble:Not a SESAME device, skip.
WARNING:pysesameos2.ble:Not a SESAME device, skip.
WARNING:pysesameos2.ble:Not a SESAME device, skip.
WARNING:pysesameos2.ble:Not a SESAME device, skip.
INFO:pysesameos2.ble:Scan completed: found 0 devices
```

Is there anything to do to discover SESAME4 with discover.py?

Thanks.

### Additional context - その他

 - I can discover SESAME3 with discover.py
 - I regist SESAME4 to Android SESAME APP, and it works properly.
 - I tried to reinstall OS(Rasbian) and re-build running enviroment with the step described in following URL.
  https://github.com/mochipon/pysesameos2/tree/main/example/mqtt2sesame

### Pysesameos2 version (`pip show pysesameos2`)

Version: 0.0.3

### Python version (`python --version`)

Python 3.7.3

### OS

Distributor ID: Raspbian Description:    Raspbian GNU/Linux 10 (buster) Release:        10 Codename:       buster

### BlueZ version (`bluetoothctl -v`) in case of Linux

bluetoothctl: 5.50

**Comment by mochipon** [comment]
I'm very happy to find someone who has SESAME 4 and is willing to use this library.
I would really appreciate if you could help me to make this library compatible with SESAME 4.

The development release is already published into Test PyPI. You can install the latest development release by the following command.

```
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pysesameos2==0.0.3.dev59
```

Could you please try this version and see if it works? Thank you!

**Comment by allfreelimeshot** [comment]
@mochipon 
Thank you for your quick response.

After installing latest development release, it works fine, and I can discover SESAME4 with discover.py!

```
$ python discover.py

==========
SESAME device found: ********-****-****-****-************

BLE Device Identifier: **:**:**:**:**:**
RSSI: -**
Device Model: CHProductModel.SS4
Device is registered on the SESAME cloud?: True
==========
````

And I confirmed pysesameos2 and mqtts2esame work well as far as my usage.

Thank you very much:heart_eyes:

**Comment by mochipon** [comment]
Great to see that!

I will then release v0.0.4 officially in #26. Thanks!
