### ISSUE TITLE
[Request]: mqttにおけるsesameの情報取得について

### ISSUE THREAD

**Issue by Syu-syusan** [mochipon/pysesameos2#36]
### Describe the solution you'd like - リクエストの内容

初めまして。
当方、こちらのプロジェクトを用いて、mqttでのsesame4の内部情報の取得を試みようとしているものです。
`pysesameos2/example/mqtt2sesame/`　のほうを拝見しまして、mqtt経由でのsesameの状態（lockかunlockか）の取得はできたのですが、sesameのバッテリー残量の取得が未だ叶っておりません。

### What's the problem this feature will solve? - 解決したい内容

もしこのプロジェクトでそもそも可能なのであれば、その方法についてご教授いただければ幸いです。
よろしくお願いします。

**Comment by mochipon** [comment]
はじめまして。このプロジェクトに関心を持って頂きありがとうございます！

さて、結論から申し上げると MQTT に SESAME のバッテリー残量を出力するようなプログラムは作成可能です。`mqtt2sesame` では、SESAME から情報を受け取ったときに `onSesameStateChanged` にて MQTT サーバに対する情報の送信 (`mqtt_client.publish`) を行います。

https://github.com/mochipon/pysesameos2/blob/63a7f93144ba11ed49be6751cb1d6b247e704fb1/example/mqtt2sesame/mqtt2sesame.py#L96-L113

例えば、この関数内で以下のような処理を追加することでバッテリーに関する情報が送信されるかと思いますが、お試しいただけますでしょうか？
（申し訳ありませんが動作確認しておらず、もし動きませんでしたらエラーを添えてお知らせくださいませ）

```python
    publishing_mechstatus = {
        "battery_remaining_percentage": device.getMechStatus().getBatteryPrecentage(),
        "battery_voltage": device.getMechStatus().self.getBatteryVoltage()
    }
    
    for topic_name, value in publishing_mechstatus.items():
        topic = "{}/{}/{}".format(config["mqtt"]["topic_prefix"], device.deviceId, topic_name)
        logger.info("Publish a message: topic={}, payload={}".format(topic, value))
        mqtt_client.publish(topic, payload=value, qos=1, retain=True)
```

**Comment by Syu-syusan** [comment]
mochiponさん

ご返信ありがとうございます。
ご返信いただきました内容の記述を追加したのですが、エラーとなってしまい、そもそもSESAMEへの接続ができなくなってしまいました。
以下、エラー内容になります。
`INFO:__main__:Connect to the MQTT server: 127.0.0.1
WARNING:__main__:Connection retry: BLE UUID = ・・・
WARNING:__main__:Connection retry: BLE UUID = ・・・
WARNING:__main__:Connection retry: BLE UUID = ・・・
WARNING:__main__:Connection retry: BLE UUID = ・・・`

**Comment by mochipon** [comment]
大変恐縮ながら、追加いただいたプログラムは BLE との接続について影響しない部分です。。。

これまで動作していたのであれば念の為に実行している環境を再起動する、更に通信品質改善のために SESAME との距離を近づける、などをお試しいただけますか？

**Comment by Syu-syusan** [comment]
自分もそう思いまして、再起動したり、近づけたりして行ってみました。しかしうまくいかずでして。
試しに、`device.getMechStatus()`だけで試してみたところ、すべてのデバイス情報（バッテリー残量、回転角など）の取得ができました。
でもやはり、`device.getMechStatus().getBatteryPrecentage()`などとすると、動作しません。
なぜなのでしょうか....エラーとかを吐くならまだわかるのですが...

**Comment by mochipon** [comment]
@Syu-syusan さん「`device.getMechStatus()` だけで試すとうまくいく」という情報をいただきありがとうございます。おかげさまで被疑箇所に気づきました。

先日共有した snippet に typo がありました。修正しましたので、もう一度お試しいただけますでしょうか？ https://github.com/mochipon/pysesameos2/issues/36#issuecomment-1021732319

**Comment by Syu-syusan** [comment]
修正ありがとうございます。
しかし、うまくいかずでして、現状すべてのデバイス情報が取れるソースコードの`onSesameStateChanged`の部分を共有させていただきます。
`def onSesameStateChanged(device: CHDevices) -> None:
    global mqtt_client, config
    logger.info(
        "SESAME status changed: SESAME UUID={}, status={}, {}".format(
            device.deviceId, device.getDeviceStatus(), device.getMechStatus()
        )
    )

    topic = "{}/status".format(config["mqtt"]["topic_prefix"])
    payload = None
    if device.getDeviceStatus() == CHSesame2Status.Locked:
        payload = "LOCKED"
    elif device.getDeviceStatus() == CHSesame2Status.Unlocked:
        payload = "UNLOCKED"

    if payload:
        logger.info("Publish a message: topic={}, payload={}".format(topic, payload))
        mqtt_client.publish(topic, payload=payload, qos=1, retain=True)
`

このようにいたしますと、`logger.info`においてデバイスの情報がすべて表示されるのですが、`device.getMechStatus().getBatteryPrecentage()`のようにすると、デバイスの情報が表示されますところにNoneと表示されてしまいます。このことから、`getBatteryPrecentage()`という指定がよくないと考えているのですが、何か心当たりありますでしょうか？

**Comment by mochipon** [comment]
詳細な情報をありがとうございます！
実機にて確認しますのでいましばらくお待ち下さい。直ぐに回答ができず大変申し訳ありません。

**Comment by mochipon** [comment]
おまたせしました。以下で動作しましたのでご確認いただけますか？

```python
    if device.getMechStatus():
        publishing_mechstatus = {
            "battery_remaining_percentage": device.getMechStatus().getBatteryPrecentage(),
            "battery_voltage": device.getMechStatus().getBatteryVoltage()
        }

        for topic_name, value in publishing_mechstatus.items():
            topic = "{}/{}/{}".format(config["mqtt"]["topic_prefix"], device.deviceId, topic_name)
            logger.info("Publish a message: topic={}, payload={}".format(topic, value))
            mqtt_client.publish(topic, payload=value, qos=1, retain=True)
```

**Comment by Syu-syusan** [comment]
mochiponさん
貴重なお時間いただき、本当にありがとうございます。こちらにて動きますことを確認いたしました。
ありがとうございます。
もしよろしければ、詳しい原因など後ほどお聞かせいただければと思います。
今回はご教授いただき本当にありがとうございました。

**Comment by mochipon** [comment]
`onSesameStateChanged` はスクリプトから見て「デバイス (との接続) の状態が変化した」ときに実行されるコールバック関数ですが、より具体的にはデバイスの `CHSesame2Status` が変化したときに実行されます。この状態遷移は [公式 SDK のドキュメント](https://doc.candyhouse.co/ja/flow_charts#sesame-%E7%8A%B6%E6%85%8B%E9%81%B7%E7%A7%BB%E5%9B%B3) がわかりやすいので参考にして下さい。

さて、`mqtt2sesame.py` では以下のように、デバイスの接続やログインを行う**前**に、このコールバック関数を登録します。

https://github.com/mochipon/pysesameos2/blob/63a7f93144ba11ed49be6751cb1d6b247e704fb1/example/mqtt2sesame/mqtt2sesame.py#L39-L44

このおかげでデバイスの接続やログインの過程で (`CHSesame2Status` が変化していくため) `onSesameStateChanged` は実行されますから、ログでは `noBleSignal` から例えば `Locked` に至るまで、状態が遷移していく様子を見ることができます。

```
INFO:__main__:SESAME status changed: SESAME UUID=xxx, status=CHSesame2Status.BleConnecting
INFO:__main__:SESAME status changed: SESAME UUID=xxx, status=CHSesame2Status.WaitingGatt
INFO:__main__:SESAME status changed: SESAME UUID=xxx, status=CHSesame2Status.BleLogining
INFO:__main__:SESAME status changed: SESAME UUID=xxx, status=CHSesame2Status.Locked
```

ここで問題になるのは、デバイスに対する `getMechStatus` で鍵の状態やバッテリーの情報が取得できるのは **デバイスへのログインに成功した後** であることです。言い換えれば、`CHSesame2Status.BleLogining` 以前の状態では `getMechStatus` を実行しても常に `None` が返ります。これが https://github.com/mochipon/pysesameos2/issues/36#issuecomment-1021732319 の snippet では問題が発生していた原因です。`None` に対して `getBatteryPrecentage()` などを実行しようとしていたわけですから、もちろん例外が発生してしまいます...

このような背景があって、既存のスクリプトでは以下のように `device.getDeviceStatus()` (`CHSesame2Status`) の絞り込みを行って MQTT サーバへの publish を行っていました。

https://github.com/mochipon/pysesameos2/blob/63a7f93144ba11ed49be6751cb1d6b247e704fb1/example/mqtt2sesame/mqtt2sesame.py#L105-L111

わたしが覚えていれば、もしくはそもそも、きちんとコメントを書いておくべきでしたが、、、https://github.com/mochipon/pysesameos2/issues/36#issuecomment-1021732319 にて「`None`と表示されてしまいます」という情報をいただき思い至りました。ありがとうございました。近々のバージョンアップではもう少しサンプルスクリプトにコメントを増やしておきます 😅

**Comment by Syu-syusan** [comment]
ご返信いただきありがとうございます。
自分の中で理解できました。
ところで、このライブラリなのですが、事実上、SESAMEのセキュリティを完全に破ってしまっていると思うのですが大丈夫なのでしょうか？
例えば、第三者がこのライブラリを用いてBLE通信によってデバイスUUIDを入手し、鍵の解錠のMQTTでのPUBLISHを行うことで開けられてしまうということに繋がってしまうと思うのですがどうなのでしょうか...？

**Comment by mochipon** [comment]
@Syu-syusan  さん

> ところで、このライブラリなのですが、事実上、SESAMEのセキュリティを完全に破ってしまっていると思うのですが大丈夫なのでしょうか？

このライブラリ (`pysesameos2`) に SESAME のセキュリティを破るような能力はありません。公式 SDK と同様の振る舞いを行う (同じように Bluetooth のパケットを送信し、受け取ったものを同じように処理する) という点で、このライブラリでできることは公式の SDK やアプリでも同様に行うことができます。このライブラリが Bluetooth 経由で SESAME を制御するためには、それ相応の認証情報 (`secret_key` など) が必須であり、それらはユーザの責任によって厳密に管理されるべきです。言い換えれば、認証情報が漏洩した場合、このライブラリに限らず、公式アプリを使って SESAME を任意に制御されてしまう恐れがあります。

もし `pysesameos2` を使うことで **SESAME デバイスにおけるセキュリティ上の問題** を発見した場合は、製造元に適切な方法で直接通報するか、[JPCERT/CC](https://www.jpcert.or.jp/) のような機関に調整を依頼してください。（個人的な経験では後者がおすすめです 😅）

> 例えば、第三者がこのライブラリを用いてBLE通信によってデバイスUUIDを入手し、鍵の解錠のMQTTでのPUBLISHを行うことで開けられてしまうということに繋がってしまうと思うのですがどうなのでしょうか...？

これは全くご懸念のとおりです。

SESAME のデバイス UUID はこのライブラリを使わずとも、例えば App Store, Google Play Store で公開されている Bluetooth スキャナと呼ばれるようなアプリを使うことで、かんたんに取得することが出来ます。もし攻撃者が `mqtt2sesame` が接続する MQTT サーバに接続できれば、解錠することが出来てしまうでしょう。

つまり、SESAME デバイスは `secret_key` などによって認証・認可を行っていますが、いうまでもなく MQTT サーバでも同等以上のセキュリティに対する考慮が必要です。

https://github.com/mochipon/pysesameos2/blob/63a7f93144ba11ed49be6751cb1d6b247e704fb1/example/mqtt2sesame/README.md#L9-L15

**Comment by Syu-syusan** [comment]
@mochipon さん
度重なるご返信ありがとうございます。
また勘違いしていた部分のご指摘もありがとうございます。
最後にもう一点よろしいでしょうか？
関数内をよく見てみると、
https://github.com/mochipon/pysesameos2/blob/63a7f93144ba11ed49be6751cb1d6b247e704fb1/example/mqtt2sesame/mqtt2sesame.py#L126
において、該当するmqttのmessageが届いた際にUUIDキーとcmdのみで解施錠を行っているように見えるのですが、これは結果としてそもそもMQTTサーバーに接続しなくても解施錠行えるという認識でよろしいのでしょうか？

**Comment by mochipon** [comment]
@Syu-syusan  さん、とんでもないことです。しっかりとしたドキュメントがありませんから、このように公開された場所で議論や情報共有が行われることは大変有意義なことだと思います。

`pysesameos2` は SESAME デバイスと BLE で通信するためのライブラリです。`mqtt2sesame` は `pysesameos2` を使って SESAME デバイスと通信しながら、MQTT サーバに通信しています。つまり、以下のようなものです。

**SESAME デバイス** <- Bluetooth -> **`pysesameos2` mqtt2sesame.py `paho.mqtt.client`** <- MQTT -> **MQTT サーバ**


> 該当するmqttのmessageが届いた際にUUIDキーとcmdのみで解施錠を行っているように見えるのですが

以下のコードは、MQTT で受け取った情報、つまり `UUID` と操作 `LOCK/UNLOCK` を `cmd_queue` というキューに追加しています。

https://github.com/mochipon/pysesameos2/blob/63a7f93144ba11ed49be6751cb1d6b247e704fb1/example/mqtt2sesame/mqtt2sesame.py#L126

キューされた処理は以下のコードで処理 (デキュー) されます。

https://github.com/mochipon/pysesameos2/blob/63a7f93144ba11ed49be6751cb1d6b247e704fb1/example/mqtt2sesame/mqtt2sesame.py#L166-L175

これだけ見ると、たしかに UUID と cmd のみで鍵操作を行っているように見えますが、`mqtt2sesame.py` を実行すると、まず `connect_sesame` にて SESAME との接続・認証（ログイン）を行っています。つまり、[状態遷移図](https://doc.candyhouse.co/ja/flow_charts#sesame-%E7%8A%B6%E6%85%8B%E9%81%B7%E7%A7%BB%E5%9B%B3) でいうところ `bleLogining` の後までは MQTT でメッセージを受け取らずとも進んでいるということです。

https://github.com/mochipon/pysesameos2/blob/63a7f93144ba11ed49be6751cb1d6b247e704fb1/example/mqtt2sesame/mqtt2sesame.py#L43-L44

あらかじめ `secret_key` などを使いながら認証することで SESAME デバイスとのコネクションを作っていますから、MQTT サーバから cmd を受け取ると、即時鍵操作ができる、というカラクリです。

**Comment by Syu-syusan** [comment]
@mochipon さん
ご返信遅れて大変申し訳ございません。
このプロジェクトのすべての理解をしました。本当にありがとうございました。
おかげさまでSESAMEへの理解が大変深まりました。貴重なお時間をお取りさせてしまったこと、深くお詫び申し上げます。
同時に、このプロジェクトを通して多大なる貢献を社会へしているのは素晴らしいことだと思います。自分にお役に立てることがあれば、なにかしらの形で携われればと思いますので、また機会がありましたらよろしくお願いいたします。
今回は本当にありがとうございました。
