### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Syu-syusan** [mochipon/pysesameos2#38]
### Describe the question you have - 質問の内容

たびたび失礼いたします。
こちらのpyysesameos2のライブラリは、pybleを用いていると思ったのですが、電波強度は具体的にはどれくらいの強度なのでしょうか？
よろしければなにかご知識ありましたら教えて頂けますと幸いです。
よろしくお願いいたします。

### Additional context - その他

例えば、自分の環境でraspberry piを用いて調査したところ、一直線上になにも遮蔽物がない場合には通常通り動くのですが、壁一枚隔ててしまった場合には動かなくなってしまいました。
SESAMEのRSSIにもよると思うのですが...

### Pysesameos2 version (`pip show pysesameos2`)

 Python 3.9.6（maybe...）

### Python version (`python --version`)

latest

### OS

Raspberry pi

**Comment by mochipon** [comment]
@Syu-syusan さん、こんにちは。

以下、ご質問の意図に沿っていればよいのですが、、、、インラインで回答いたしますね。

> こちらのpyysesameos2のライブラリは、pybleを用いていると思ったのですが、電波強度は具体的にはどれくらいの強度なのでしょうか？

`pysesameos2` は [bleak](https://github.com/hbldh/bleak) が提供する cross-platform な Python API を経由して、実行環境の BLE プロトコルスタック (例えば Linux なら BlueZ) にアクセスします。したがって、実際に電波を送信するような処理には関わっておりません。

**電波強度** が `pysesameos2` が SESAME に対して送信する **電波の強さ** であるならば「実行環境に依存します」としか回答できません。もし Raspberry Pi 上で Linux を実行しているのであれば、Raspberry Pi のチップや Linux カーネルのドライバ、BlueZ のパラメータなどで決定されるのかもしれませんが、いずれにしても `pysesameos2` では操作することができません。

> 例えば、自分の環境でraspberry piを用いて調査したところ、一直線上になにも遮蔽物がない場合には通常通り動くのですが、壁一枚隔ててしまった場合には動かなくなってしまいました。

[example/discover.py](https://github.com/mochipon/pysesameos2/blob/main/example/discover.py) は RSSI (SESAME の電波をどれくらいの電波の強さで受信できているか) を表示してくれます。しかし RSSI は相対的な指標であるため、正常に通信するのに必要な最小信号強度は環境によって異なります。

正常に動作するギリギリの RSSI を維持できる設置場所を検討するか、はたまた、TX/RX power の大きな bluetooth ドングルを取り付けるか（しかし技適を踏まえると今より改善するのか怪しい）、、、そのような検討になろうかと思います。

**Comment by Syu-syusan** [comment]
ご返信大変遅くなり、申し訳ございません。
あれから色々と試し、使用しているラズパイのbleが弱いので、USB bleアダプターでセサミと通信したいと考えました。一方、ラズパイにbleアダプタをさしてpysesame起動すると必ずラズパイの組み込みのbleでセサミと通信してしまい、ラズパイはアダプタを認識しており、blutoothctlからペアリングしたりもできるので、おそらくpysesameos2で呼んでるble関連のライブラリを書き換える必要があると考えたのですが、どこを設定すればいいか分からずでして...
なにか有効な手法をご存知でしたらご教授いただけると幸いです。
よろしくお願いします。

**Comment by mochipon** [comment]
`pysesameos2` が利用している `bleak` では [インターフェイス (`adapter`) の選択ができる](https://bleak.readthedocs.io/en/latest/api.html#bleak.backends.bluezdbus.client.BleakClientBlueZDBus) ようですが、コレを使うためには、そこそこの変更が必要になりそうです。
例えば、オンボードの Bluetooth を無効にすることで回避するのはいかがでしょうか？`/boot/config.txt` に `dtoverlay=disable-bt` を追記するだけなので、比較的楽かつ確実な方法ではないかと...

**Comment by Syu-syusan** [comment]
@mochipon さん

多忙につき、返信が遅れてしまいまして申し訳ございません。
試行錯誤の末、無事にうまく動作させることができました...
本当にありがとうございました。
